class_name BalanceConfig
extends Node

const STARTING_CREDITS := 100.0
const PASSIVE_INCOME_PER_SECOND := 5.0

const COST_ANALYST_BATCH := 10.0
const ANALYSTS_PER_BATCH := 3

const COST_AUDITOR_HERO := 50.0
const AUDITOR_RESPAWN_COOLDOWN := 10.0

const COST_TOWER_UPGRADE_L1_TO_L2 := 20.0
const COST_TOWER_UPGRADE_L2_TO_L3 := 40.0

const KILL_REWARD_UNIT := 2.0
const KILL_REWARD_TOWER := 10.0
const KILL_REWARD_HQ := 50.0
const KILL_REWARD_ACCENTURE_MOB := 8.0
